export const metadata = {
  title: "Disclaimer — TradeSharp",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-4xl font-bold text-text-primary mb-2">
        Disclaimer
      </h1>
      <p className="text-text-secondary mb-10">Last updated: June 2025</p>

      <div className="prose prose-invert max-w-none space-y-8 text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            1. Not Financial or Betting Advice
          </h2>
          <p>
            TradeSharp (&quot;the Service&quot;) provides AI-generated analysis of
            uploaded market screenshots for informational and entertainment
            purposes only. Nothing on this platform constitutes financial
            advice, investment advice, betting advice, or any other form of
            professional advisory service. The signals, recommendations,
            confidence scores, and reasoning provided are generated by
            automated systems and should not be relied upon as the sole basis
            for any trading, betting, or investment decision.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            2. No Guarantee of Accuracy
          </h2>
          <p>
            The AI analysis provided by TradeSharp is based on patterns
            detected in uploaded images and simulated market knowledge. We
            make no representation or warranty of any kind, express or
            implied, regarding the accuracy, completeness, reliability, or
            suitability of any analysis, recommendation, or signal. Market
            conditions can change rapidly, and past patterns do not guarantee
            future results.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            3. Risk of Loss
          </h2>
          <p>
            Trading, betting, and investing in prediction markets involves
            substantial risk of financial loss. You may lose all or more than
            your initial investment. Only participate in markets with money
            you can afford to lose. TradeSharp bears no responsibility for
            any financial losses incurred as a result of using this service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            4. Limitations of AI Analysis
          </h2>
          <p>
            Our AI system analyzes only what is visible in the uploaded
            screenshot. It cannot account for information not present in the
            image, real-time market changes, news events, or other factors
            that may affect market outcomes. The quality of analysis is
            directly dependent on the clarity and completeness of the
            uploaded image.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            5. Jurisdictional Compliance
          </h2>
          <p>
            Sports betting, prediction markets, and financial trading are
            regulated differently across jurisdictions. It is your sole
            responsibility to ensure that your use of this service and any
            markets you participate in comply with the laws of your
            jurisdiction. TradeSharp does not facilitate any actual betting or
            trading activity.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            6. Responsible Gambling
          </h2>
          <p>
            If you or someone you know has a gambling problem, please seek
            help. Resources include:
          </p>
          <ul className="list-disc list-inside space-y-1 mt-2">
            <li>National Problem Gambling Helpline: 1-800-522-4700</li>
            <li>Gamblers Anonymous: www.gamblersanonymous.org</li>
            <li>NCPG: www.ncpgambling.org</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            7. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, TradeSharp,
            its operators, employees, and affiliates shall not be liable for
            any indirect, incidental, special, consequential, or punitive
            damages, including without limitation loss of profits, data, or
            goodwill, arising from your use of the Service, regardless of
            whether we have been advised of the possibility of such damages.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            8. Changes to This Disclaimer
          </h2>
          <p>
            We reserve the right to update this disclaimer at any time.
            Continued use of TradeSharp after any changes constitutes
            acceptance of the updated disclaimer.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary mb-3">
            9. Contact
          </h2>
          <p>
            For questions about this disclaimer, please contact us through
            the platform.
          </p>
        </section>
      </div>
    </div>
  );
}
